sudo: required
dist: trusty
os:
  - linux
  #- osx

addons:
  apt:
    sources:
      # later we can test with current, now we want stable
      #- chef-current-precise
      - chef-stable-precise
    packages:
      - chefdk
      #- git
      #- squid

before_install:
  - sudo apt-get -y install squid3 git curl wget

# Ensure we make ChefDK's Ruby the default
before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"

env:
  global:
    - PROXY_TESTS_DIR=files/default/scripts
    - PROXY_TESTS_REPO=$PROXY_TESTS_DIR/repo

script:
  - chef-client --version
  - sudo -E bash $PROXY_TESTS_DIR/run_tests.sh \* \* \* /tmp/out.txt

after_script:
  - cat /tmp/out.txt
