sudo: required
dist: trusty
os:
  - linux
  #- osx

addons:
  apt:
    sources:
      # later we can test with current, now we want stable
      - chef-current-precise
      #- chef-stable-precise
    packages:
      - chefdk
      #- git
      #- squid

before_install:
  - sudo apt-get -y install squid3 git curl wget

# Ensure we make ChefDK's Ruby the default
before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"

env:
  global:
    - PROXY_TESTS_DIR=/tmp/proxy_tests
    - PROXY_TESTS_REPO=$PROXY_TESTS_DIR/repo

script:
  - chef-client --version
  # We need these gems to test Test Kitchen proxy connectivity
  - chef gem install "kitchen-ec2"
  # We render the files for the test specifically for the sake of the Berkshelf
  # tests, since we need to write out a config.json that includes the absolute
  # path to a client key, but we don't know the $PROXY_TESTS_REPO path until
  # this runs.
  - chef-client -z -o proxy_tests::render
  - sudo -E bash $PROXY_TESTS_DIR/run_tests.sh \* \* \* /tmp/out.txt

after_script:
  - cat /tmp/out.txt
  - sudo cat /var/log/squid3/cache.log
  - sudo cat /var/log/squid3/access.log
